version: '3.8'
services:

  worker: &worker
    image: hugocker/top-1m-jarm-v2
    container_name: top-1m-jarm-v2-worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - RUST_BACKTRACE=1
      # - SENTRY_DSN=XXX
    command: ["-v", "worker"]

  scheduler:
    <<: *worker
    container_name: top-1m-jarm-v2-scheduler
    command: ["-v", "scheduler"]

  uploader:
    <<: *worker
    container_name: top-1m-jarm-v2-uploader
    command: ["-v", "uploader"]

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

