version: '3.8'
services:

  worker: &worker
    image: hugocker/top-1m-jarm-v2
    container_name: top-1m-jarm-v2-worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - RUST_BACKTRACE=1
#      - SENTRY_DSN=XXX
    command: ["-v", "worker"]
    deploy:
      resources:
        limits:
          memory: 100M
      mode: replicated
      replicas: 0
      update_config:
        parallelism: 1  # To reduce disk load
        delay: 1s
      restart_policy:
        condition: none

  scheduler:
    <<: *worker
    container_name: top-1m-jarm-v2-scheduler
    command: ["-v", "scheduler"]
    deploy:
      resources:
        limits:
          memory: 100M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

  uploader:
    <<: *worker
    container_name: top-1m-jarm-v2-uploader
    environment:
      - REDIS_HOST=redis
      - RUST_BACKTRACE=1
#      - SENTRY_DSN=XXX
      - AWS_ACCESS_KEY_ID=XXX
      - AWS_SECRET_ACCESS_KEY=XXX
    command: ["-v", "uploader"]
    deploy:
      resources:
        limits:
          memory: 100M
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    deploy:
      resources:
        limits:
          memory: 500M

