name: Rust Check & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: rustcache
      uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check --verbose
    - name: Test
      run: cargo test
    - name: Test E2E
      run: make docker-test-e2e
    - name: Run Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features